openapi: 3.0.3
info:
  title: File to Markdown Converter API
  version: "1.0.1"
  description: >
    An API that converts files (PDF, PPTX, DOCX, HTML) into Markdown.
    Clients can upload files either via multipart/form-data or by sending the raw binary 
    with the corresponding MIME type.
paths:
  /convert/pdf:
    post:
      summary: Convert PDF to Markdown
      description: Accepts a PDF file and returns its content as Markdown.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The PDF file to convert.
              required:
                - file
            encoding:
              file:
                contentType: application/pdf
          application/pdf:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Markdown conversion successful
          content:
            text/markdown:
              schema:
                type: string
              example: |
                # Converted Markdown from PDF
                This is a sample markdown output.
        '400':
          description: Invalid input or conversion error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid file format or conversion failed."
  /convert/pptx:
    post:
      summary: Convert PPTX to Markdown
      description: Accepts a PPTX file and returns its content as Markdown.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The PPTX file to convert.
              required:
                - file
            encoding:
              file:
                contentType: application/vnd.openxmlformats-officedocument.presentationml.presentation
          application/vnd.openxmlformats-officedocument.presentationml.presentation:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Markdown conversion successful
          content:
            text/markdown:
              schema:
                type: string
              example: |
                # Converted Markdown from PPTX
                This is a sample markdown output.
        '400':
          description: Invalid input or conversion error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid file format or conversion failed."
  /convert/docx:
    post:
      summary: Convert DOCX to Markdown
      description: Accepts a DOCX file and returns its content as Markdown.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The DOCX file to convert.
              required:
                - file
            encoding:
              file:
                contentType: application/vnd.openxmlformats-officedocument.wordprocessingml.document
          application/vnd.openxmlformats-officedocument.wordprocessingml.document:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Markdown conversion successful
          content:
            text/markdown:
              schema:
                type: string
              example: |
                # Converted Markdown from DOCX
                This is a sample markdown output.
        '400':
          description: Invalid input or conversion error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid file format or conversion failed."
  /convert/html:
    post:
      summary: Convert HTML to Markdown
      description: Accepts an HTML file and returns its content as Markdown.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The HTML file to convert.
              required:
                - file
            encoding:
              file:
                contentType: text/html
          text/html:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Markdown conversion successful
          content:
            text/markdown:
              schema:
                type: string
              example: |
                # Converted Markdown from HTML
                This is a sample markdown output.
        '400':
          description: Invalid input or conversion error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid file format or conversion failed."
