openapi: 3.0.3
info:
    title: File to Markdown Converter API
    version: 1.0.1
    description: >
        An API that converts files (PDF, PPTX, DOCX, HTML) into Markdown. Clients can upload files either via
        multipart/form-data or by sending the raw binary  with the corresponding MIME type.
paths:
    /convert/pdf:
        post:
            requestBody:
                content:
                    application/pdf:
                        schema:
                            format: binary
                            type: string
                required: true
            responses:
                '200':
                    content:
                        text/markdown:
                            schema:
                                type: string
                            example: |
                                # Converted Markdown from PDF
                                This is a sample markdown output.
                    description: Markdown conversion successful
                '400':
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Invalid file format or conversion failed.
                    description: Invalid input or conversion error
                '500':
                    content:
                        application/json: {}
                    description: Internal server error
            summary: Convert PDF to Markdown
            description: Accepts a PDF file and returns its content as Markdown.