# coding: utf-8

"""
    File to Markdown Converter API

    An API that converts files (PDF and Images) into Markdown. Clients can upload files either via multipart/form-data or by sending the raw binary  with the corresponding MIME type. 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from langchain_ocr.apis.ocr_api import router as DefaultApiRouter
from langchain_ocr.dependency_container import DependencyContainer

from langchain_ocr.impl import ocr_api

app = FastAPI(
    title="File to Markdown Converter API",
    description="An API that converts files (PDF and Images) into Markdown. Clients can upload files either via multipart/form-data or by sending the raw binary  with the corresponding MIME type. ",
    version="1.0.1",
)

app.include_router(DefaultApiRouter)


container = DependencyContainer()
container.wire(modules=[ocr_api])
app.container = container