[tool.poetry]
name = "langchain-ocr-lib"
version = "0.1.0"
description = ""
authors = ["Andreas Klos <aklos@outlook.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
