# coding: utf-8

"""
    File to Markdown Converter API

    An API that converts files (PDF, PPTX, DOCX, HTML) into Markdown. Clients can upload files either via multipart/form-data or by sending the raw binary  with the corresponding MIME type. 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from langchain_ocr.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="File to Markdown Converter API",
    description="An API that converts files (PDF, PPTX, DOCX, HTML) into Markdown. Clients can upload files either via multipart/form-data or by sending the raw binary  with the corresponding MIME type. ",
    version="1.0.1",
)

app.include_router(DefaultApiRouter)
